[2024-10-10 16:15:50,961] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.boxplot_data_receipt 2024-10-10T16:13:17.159947+00:00 [queued]>
[2024-10-10 16:15:50,973] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.boxplot_data_receipt 2024-10-10T16:13:17.159947+00:00 [queued]>
[2024-10-10 16:15:50,974] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 16:15:50,974] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 16:15:50,975] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 16:15:50,981] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): boxplot_data_receipt> on 2024-10-10T16:13:17.159947+00:00
[2024-10-10 16:15:50,986] {standard_task_runner.py:52} INFO - Started process 82944 to run task
[2024-10-10 16:15:50,989] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'boxplot_data_receipt', '2024-10-10T16:13:17.159947+00:00', '--job-id', '541', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmpm5m3hgqz', '--error-file', '/tmp/tmp9r3lmvxp']
[2024-10-10 16:15:50,992] {standard_task_runner.py:77} INFO - Job 541: Subtask boxplot_data_receipt
[2024-10-10 16:15:51,021] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.boxplot_data_receipt 2024-10-10T16:13:17.159947+00:00 [running]> on host da843a407010
[2024-10-10 16:15:51,051] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=boxplot_data_receipt
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T16:13:17.159947+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T16:13:17.159947+00:00
[2024-10-10 16:15:51,054] {logging_mixin.py:104} INFO - Empty DataFrame
Columns: []
Index: []
[2024-10-10 16:15:51,055] {logging_mixin.py:104} INFO - Error generating boxplot: "The following columns are missing from the receipt DataFrame: ['PAY_PERD', 'PAY_AMT1', 'PAY_AMT2']"
[2024-10-10 16:15:51,056] {python.py:151} INFO - Done. Returned value was: None
[2024-10-10 16:15:51,062] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=mssql_dag, task_id=boxplot_data_receipt, execution_date=20241010T161317, start_date=20241010T161550, end_date=20241010T161551
[2024-10-10 16:15:51,075] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10 16:15:51,081] {local_task_job.py:149} INFO - Task exited with return code 0
