[2024-10-10 04:39:33,536] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.check_null_contract 2024-10-10T04:39:27.817496+00:00 [queued]>
[2024-10-10 04:39:33,544] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: mssql_dag.check_null_contract 2024-10-10T04:39:27.817496+00:00 [queued]>
[2024-10-10 04:39:33,545] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 04:39:33,545] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-10-10 04:39:33,545] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-10 04:39:33,554] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): check_null_contract> on 2024-10-10T04:39:27.817496+00:00
[2024-10-10 04:39:33,559] {standard_task_runner.py:52} INFO - Started process 33480 to run task
[2024-10-10 04:39:33,561] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mssql_dag', 'check_null_contract', '2024-10-10T04:39:27.817496+00:00', '--job-id', '440', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mssql_dag.py', '--cfg-path', '/tmp/tmp8v9r741p', '--error-file', '/tmp/tmput0nif22']
[2024-10-10 04:39:33,564] {standard_task_runner.py:77} INFO - Job 440: Subtask check_null_contract
[2024-10-10 04:39:33,604] {logging_mixin.py:104} INFO - Running <TaskInstance: mssql_dag.check_null_contract 2024-10-10T04:39:27.817496+00:00 [running]> on host da843a407010
[2024-10-10 04:39:33,653] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mssql_dag
AIRFLOW_CTX_TASK_ID=check_null_contract
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T04:39:27.817496+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T04:39:27.817496+00:00
[2024-10-10 04:39:33,703] {python.py:151} INFO - Done. Returned value was: PROM_MEMB_NO                 0
PROM_LOAN_TYPE               0
PROM_YY                      0
PROM_NO                      0
PROM_LOAN_BRH                0
PROM_LOAN_YMD                0
PROM_LOAN_AMT                0
PROM_LOAN_PERD               0
PROM_LOAN_PERD_AMT           0
PROM_LAST_YMD                0
PROM_PAID_AMT                0
PROM_PAID_INT                0
PROM_PAID_PERD               0
PROM_PAID_TIME               0
PROM_PAID_STS                0
PROM_CODERATE                0
PROM_COND_TYPE               0
PROM_PERD_AMT                0
PROM_REAL_AMT                0
PROM_RECV_AMT                0
PROM_RECV_YMD                0
PROM_RECV_TIME               0
PROM_REASON                  0
PROM_WITH_MEMBNO             0
PROM_WITH_TYPE               0
PROM_INT_YMD                 0
PROM_ACCU_INT                0
PROM_SPEC_TYPE               0
PROM_AMT_YMD                 0
PROM_RET_INT                 0
PROM_NPAY_INT                0
PROM_REQ_STS                 0
PROM_PAY_STS                 0
PROM_DUE_DATE              102
PROM_CHK_RIGHT               0
PROM_IS_CALL_AVG_INT         0
PROM_IS_CALL_ACCUED_INT      0
PROM_STOP_AMT_STS            0
PROM_NPL_CODE                0
PROM_DEBT_STS                0
PROM_DEBT_DUE_DATE           0
PROM_START_PAY               0
PROM_IS_CANCEL               0
PROM_PAID_MONTH_AMT          0
PROM_FUND_AMT                0
PROM_FUND_PAID_AMT           0
PROM_INT2_BAL                0
PROM_PERD_AMT_ADD            0
PROM_PERD_AMT_ADD_NEXT      19
PROM_OP_CODE                 0
POST_DATETIME                0
dtype: int64
[2024-10-10 04:39:33,705] {xcom.py:229} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-10-10 04:39:33,706] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1364, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1943, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 79, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 226, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Series' is not JSON serializable
[2024-10-10 04:39:33,707] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_dag, task_id=check_null_contract, execution_date=20241010T043927, start_date=20241010T043933, end_date=20241010T043933
[2024-10-10 04:39:33,733] {local_task_job.py:149} INFO - Task exited with return code 1
